// Search targets for Stage 2. Only `description`+`intent`+`metrics`+`operations` get
// embedded (see patternText below) — `fragment_ids` is an ORDERED list (dependencies before
// the terminal step) resolved directly by ID in Stage 4, never re-embedded or re-searched.

export const queryPatterns = [
  {
    pattern_id: 'pat_activity_count_mtd', name: '활동 건수(당월, 스칼라)',
    description: '특정 딜러/SC의 이번달 CRM 활동 건수 합계를 구한다.',
    intent: ['count'], metrics: ['활동건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_activity_count_scalar'],
    source_sql_id: 'src_fs01', verified: true,
  },
  {
    pattern_id: 'pat_activity_target_mtd', name: '활동 목표(당월, 스칼라)',
    description: '특정 딜러/SC의 이번달 활동 목표(당월목표) 건수 합계를 구한다.',
    intent: ['count'], metrics: ['활동목표', '당월목표'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_CRM_TARGET_D', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_activity_target_scalar'],
    source_sql_id: 'src_fs22', verified: true,
  },
  {
    pattern_id: 'pat_activity_list_by_org', name: '활동 실적 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 활동 실적 건수를 나눠서 보여준다.',
    intent: ['breakdown'], metrics: ['활동실적'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER'],
    operations: ['join', 'filter', 'group_by', 'sum'],
    fragment_ids: ['frag_activity_list_select'],
    source_sql_id: 'src_fs02', verified: true,
  },
  {
    pattern_id: 'pat_activity_progress_rate', name: '활동 진행률(실적/목표, 스칼라)',
    description: '특정 딜러/SC의 이번달 활동 실적 대비 목표 진행률(달성률)을 구한다.',
    intent: ['ratio'], metrics: ['활동진행률', '달성률'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_CRM_TARGET_D', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER'],
    operations: ['join', 'filter', 'sum', 'ratio'],
    fragment_ids: ['frag_filtered_dates_yearmonth', 'frag_filtered_users_dealer', 'frag_filtered_types', 'frag_target_cnt_daily', 'frag_actual_cnt_activity', 'frag_activity_progress_ratio_select'],
    source_sql_id: 'src_fs03', verified: true,
  },
  {
    pattern_id: 'pat_activity_progress_list_by_org', name: '활동 진척률 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 활동 실적 대비 목표 진척률을 나눠서 보여준다.',
    intent: ['breakdown', 'ratio'], metrics: ['활동진척률'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_CRM_TARGET_D', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'group_by', 'sum', 'ratio', 'full_outer_join'],
    fragment_ids: ['frag_activity_progress_list_ac', 'frag_activity_progress_list_tgt', 'frag_activity_progress_list_select'],
    source_sql_id: 'src_fs23', verified: true,
  },
  {
    pattern_id: 'pat_lead_count_activity_basis', name: '영업기회 건수(당월활동실적 기준, 스칼라)',
    description: '특정 딜러/SC의 이번달 영업기회(리드) 건수를 구한다 — 자격 활동이 실제로 연결된 리드만 인정하는 기본 정의.',
    intent: ['count'], metrics: ['영업기회건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'exists_subquery', 'count_distinct'],
    fragment_ids: ['frag_lead_count_activity_scalar'],
    source_sql_id: 'src_fs04', verified: true,
  },
  {
    pattern_id: 'pat_lead_target_mtd', name: '영업기회 목표(당월, 스칼라)',
    description: '특정 딜러/SC의 이번달 영업기회 목표 건수를 구한다.',
    intent: ['count'], metrics: ['영업기회목표'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_CRM_TARGET_M', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_lead_target_scalar'],
    source_sql_id: 'src_fs05', verified: true,
  },
  {
    pattern_id: 'pat_lead_list_activity_basis', name: '영업기회 실적 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 영업기회(당월활동실적기준) 건수를 나눠서 보여준다.',
    intent: ['breakdown'], metrics: ['영업기회실적'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'exists_subquery', 'group_by', 'count_distinct'],
    fragment_ids: ['frag_lead_list_activity_basis_select'],
    source_sql_id: 'src_fs24', verified: true,
  },
  {
    pattern_id: 'pat_lead_target_list_by_org', name: '영업기회 목표 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 영업기회 목표를 나눠서 보여준다.',
    intent: ['breakdown'], metrics: ['영업기회목표'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_CRM_TARGET_M', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'group_by', 'sum'],
    fragment_ids: ['frag_lead_target_list_select'],
    source_sql_id: 'src_fs25', verified: true,
  },
  {
    pattern_id: 'pat_activity_lead_conversion_rate', name: '활동→영업기회 전환율(스칼라)',
    description: '이번달 활동 건수 대비 영업기회(리드) 건수의 전환율을 구한다.',
    intent: ['ratio', 'conversion'], metrics: ['활동전환율', '영업기회전환율'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'count_distinct', 'sum', 'ratio'],
    fragment_ids: ['frag_lead_count_activity_scalar', 'frag_activity_count_scalar', 'frag_lead_act_conversion_ratio_select'],
    source_sql_id: 'src_fs09', verified: true,
  },
  {
    pattern_id: 'pat_lead_progress_rate', name: '영업기회 진행률(실적/목표, 스칼라)',
    description: '이번달 영업기회 건수(당월활동실적기준) 대비 영업기회 목표의 진행률을 구한다.',
    intent: ['ratio'], metrics: ['영업기회진행률'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_CRM_TARGET_M', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'count_distinct', 'sum', 'ratio'],
    fragment_ids: ['frag_lead_count_activity_scalar', 'frag_lead_target_scalar', 'frag_lead_progress_ratio_select'],
    source_sql_id: 'src_fs10', verified: true,
  },
  {
    pattern_id: 'pat_contract_count_mtd', name: '계약 건수(당월활동실적 기준, 스칼라)',
    description: '특정 딜러/SC의 이번달 계약 건수를 구한다 — 자격 리드(qualified lead)에 연결된 계약만 인정.',
    intent: ['count'], metrics: ['계약건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_CONTRACT_KTWS', 'KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'exists_subquery', 'sum'],
    fragment_ids: ['frag_mtd_dates', 'frag_filtered_users_dealer', 'frag_activity_leads_mtd', 'frag_lead_pool_mtd', 'frag_contract_scalar'],
    source_sql_id: 'src_fs06', verified: true,
  },
  {
    pattern_id: 'pat_contract_target_list_by_org', name: '계약 목표 목록(딜러/부서/SC별)',
    description: '딜러/그룹/부서/SC별로 계약 목표를 나눠서 보여준다.',
    intent: ['breakdown'], metrics: ['계약목표'], dimensions: ['딜러', '그룹', '부서', 'SC'],
    required_tables: ['KPI_W::FCT_CRM_TARGET_M', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'group_by', 'sum'],
    fragment_ids: ['frag_contract_target_list_select'],
    source_sql_id: 'src_fs07', verified: true,
  },
  {
    pattern_id: 'pat_contract_conversion_rate', name: '영업기회→계약 전환율(스칼라)',
    description: '이번달 영업기회 건수 대비 계약 건수의 전환율을 구한다 — 자격 리드 기준.',
    intent: ['ratio', 'conversion'], metrics: ['계약전환율'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_CONTRACT_KTWS', 'KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'exists_subquery', 'count_distinct', 'sum', 'ratio'],
    fragment_ids: ['frag_qualified_lead_full', 'frag_lead_count_for_cvr', 'frag_contract_count_for_cvr', 'frag_contract_conversion_ratio_select'],
    source_sql_id: 'src_fs08', verified: true,
  },
  {
    pattern_id: 'pat_contract_list_by_org', name: '계약 실적 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 계약 실적을 나눠서 보여준다 — 자격 리드에 연결된 계약만.',
    intent: ['breakdown'], metrics: ['계약실적'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_CONTRACT_KTWS', 'KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'exists_subquery', 'group_by', 'sum'],
    fragment_ids: ['frag_qualified_lead_key', 'frag_contract_list_select'],
    source_sql_id: 'src_fs26', verified: true,
  },
  {
    pattern_id: 'pat_hboard_hot_by_sc', name: '차원별 해피보드 HOT 고객 건수',
    description: '딜러/브랜드/전시장/부서/SC 중 요청된 기준으로 이번달 해피보드 HOT 고객 건수를 구한다.',
    intent: ['count', 'breakdown'], metrics: ['HOT고객건수'], dimensions: ['딜러', '브랜드', '전시장', '부서', 'SC'],
    required_tables: ['KPI_W::FCT_HBOARD_MEETING', 'KPI_W::DIM_MNG_USER'],
    operations: ['join', 'filter', 'count', 'group_by'],
    fragment_ids: ['frag_hboard_hot_by_sc'],
    source_sql_id: 'src_fs11', verified: false,
  },
  {
    pattern_id: 'pat_hboard_status_by_variant', name: '차종별 HOT 고객 상태 분포',
    description: '관심 차종별 HOT 고객 상태 분포를 구한다.',
    intent: ['breakdown'], metrics: ['HOT고객상태분포'], dimensions: ['차종', '상태'],
    required_tables: ['KPI_W::FCT_HBOARD_MEETING', 'KPI_W::DIM_VEHIC_SPEC_VAR'],
    operations: ['join', 'count', 'group_by'],
    fragment_ids: ['frag_hboard_status_by_variant'],
    source_sql_id: 'src_fs12', verified: false,
  },
  {
    pattern_id: 'pat_mng_cust_by_sc', name: '차원별 담당 고객 수',
    description: '딜러/브랜드/전시장/부서/SC 중 요청된 기준으로 담당 고객 수를 구한다.',
    intent: ['count', 'breakdown'], metrics: ['담당고객수'], dimensions: ['딜러', '브랜드', '전시장', '부서', 'SC'],
    required_tables: ['KPI_W::FCT_MNG_CUST_LIST', 'KPI_W::DIM_MNG_USER'],
    operations: ['join', 'count', 'group_by'],
    fragment_ids: ['frag_mng_cust_by_sc'],
    source_sql_id: 'src_fs13', verified: false,
  },
  {
    pattern_id: 'pat_nps_by_biz_area', name: '사업부문별 평균 NPS',
    description: '사업부문별 이번달 평균 NPS 점수를 구한다.',
    intent: ['aggregate'], metrics: ['NPS점수'], dimensions: ['사업부문'],
    required_tables: ['KPI_W::FCT_NPS'],
    operations: ['filter', 'avg', 'group_by'],
    fragment_ids: ['frag_nps_by_biz_area'],
    source_sql_id: 'src_fs14', verified: false,
  },
  {
    pattern_id: 'pat_nps_by_sc', name: 'SC별 NPS 점수/코멘트',
    description: 'SC별 NPS 점수와 고객 코멘트를 조회한다.',
    intent: ['list'], metrics: ['NPS점수'], dimensions: ['SC'],
    required_tables: ['KPI_W::FCT_NPS', 'KPI_W::DIM_MNG_USER'],
    operations: ['join', 'sort'],
    fragment_ids: ['frag_nps_by_sc'],
    source_sql_id: 'src_fs15', verified: false,
  },
  {
    pattern_id: 'pat_sales_target_by_dealer', name: '차원별 출고/계약 목표',
    description: '딜러 또는 브랜드 중 요청된 기준으로 이번달 출고 목표와 계약 목표를 구한다.',
    intent: ['count', 'breakdown'], metrics: ['출고목표', '계약목표'], dimensions: ['딜러', '브랜드'],
    required_tables: ['KPI_W::FCT_SALES_TARGET_DAILY', 'KPI_W::DIM_MNG_DEALER'],
    operations: ['join', 'filter', 'sum', 'group_by'],
    fragment_ids: ['frag_sales_target_by_dealer'],
    source_sql_id: 'src_fs16', verified: false,
  },
  {
    pattern_id: 'pat_sales_target_trend_by_model', name: '모델별 일일 계약 목표 추이',
    description: '모델별 일일 계약 목표 추이를 조회한다.',
    intent: ['trend'], metrics: ['일일계약목표'], dimensions: ['모델', '일자'],
    required_tables: ['KPI_W::FCT_SALES_TARGET_DAILY', 'KPI_W::DIM_VEHIC_SPEC_MDL'],
    operations: ['join', 'sort'],
    fragment_ids: ['frag_sales_target_trend_by_model'],
    source_sql_id: 'src_fs17', verified: false,
  },
  {
    pattern_id: 'pat_stock_by_dealer', name: '차원별 재고 대수',
    description: '딜러 또는 브랜드 중 요청된 기준으로 재고 대수를 구한다.',
    intent: ['count', 'breakdown'], metrics: ['재고대수'], dimensions: ['딜러', '브랜드'],
    required_tables: ['KPI_W::FCT_AVAIL_STOCK', 'KPI_W::DIM_MNG_DEALER'],
    operations: ['join', 'count', 'group_by'],
    fragment_ids: ['frag_stock_by_dealer'],
    source_sql_id: 'src_fs18', verified: false,
  },
  {
    pattern_id: 'pat_vehic_spec_current', name: '판매 중인 SFX(트림) 목록',
    description: '현재 판매 중인 SFX(트림) 목록을 조회한다.',
    intent: ['list'], metrics: [], dimensions: ['모델', '차종', 'SFX'],
    required_tables: ['KPI_W::DIM_VEHIC_SPEC'],
    operations: ['filter', 'sort'],
    fragment_ids: ['frag_vehic_spec_current'],
    source_sql_id: 'src_fs19', verified: false,
  },
  {
    pattern_id: 'pat_sc_list_by_dealer', name: '딜러 소속 SC 목록',
    description: '딜러명으로 소속 SC 목록을 조회한다.',
    intent: ['list'], metrics: [], dimensions: ['딜러', 'SC'],
    required_tables: ['KPI_W::DIM_MNG_USER'],
    operations: ['filter'],
    fragment_ids: ['frag_sc_list_by_dealer'],
    source_sql_id: 'src_fs20', verified: false,
  },
  {
    pattern_id: 'pat_business_days_quarter', name: '분기 영업일수',
    description: '이번 분기 영업일수(공휴일 제외)를 구한다.',
    intent: ['count'], metrics: ['영업일수'], dimensions: ['분기'],
    required_tables: ['KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['filter', 'count'],
    fragment_ids: ['frag_business_days_quarter'],
    source_sql_id: 'src_fs21', verified: false,
  },
  // ---- fs27~fs35: 1-1시트 신규 — 당월전체실적(coalesce), 계약목표/진행률, 시승 퍼널 ----
  {
    pattern_id: 'pat_lead_count_mtd_coalesce', name: '영업기회 건수(당월전체실적, coalesce)',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 영업기회 건수를 FCT_LEAD.cnt 직접 합산으로 구한다(활동 실적 기반이 아닌 전체실적 버전).',
    intent: ['count'], metrics: ['영업기회건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_lead_mtd_coalesce_scalar'],
    source_sql_id: 'src_fs27', verified: true,
  },
  {
    pattern_id: 'pat_contract_count_mtd_coalesce', name: '계약건수(당월전체실적, coalesce)',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 계약건수를 lead 자격 판정 없이 FCT_CONTRACT_KTWS.cnt 직접 합산으로 구한다(당월활동실적 버전과 다름).',
    intent: ['count'], metrics: ['계약건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_CONTRACT_KTWS', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_cntrct_mtd_coalesce_scalar'],
    source_sql_id: 'src_fs28', verified: true,
  },
  {
    pattern_id: 'pat_contract_target_mtd', name: '계약 당월 목표(스칼라)',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 계약 목표 건수 합계를 구한다.',
    intent: ['count'], metrics: ['계약목표'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_CRM_TARGET_M', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_cntrct_mtd_target_scalar'],
    source_sql_id: 'src_fs29', verified: true,
  },
  {
    pattern_id: 'pat_contract_progress_rate', name: '계약 진행률(coalesce 버전)',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 계약 실적 ÷ 계약 목표 진행률(%)을 구한다.',
    intent: ['ratio'], metrics: ['계약진행률', '달성률'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_CONTRACT_KTWS', 'KPI_W::FCT_CRM_TARGET_M', 'KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CRM_ACT_TYPE'],
    operations: ['join', 'filter', 'sum', 'divide'],
    fragment_ids: ['frag_mtd_dates', 'frag_filtered_users_org', 'frag_activity_leads_coalesce', 'frag_lead_pool_coalesce', 'frag_cntrct_progress_ratio_org_select'],
    source_sql_id: 'src_fs30', verified: true,
  },
  {
    pattern_id: 'pat_testdrive_conversion_rate', name: '영업기회에서 시승으로 전환율',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 영업기회 대비 시승 전환율(%)을 구한다.',
    intent: ['ratio', 'conversion'], metrics: ['시승전환율'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_CRM_ACT_TYPE'],
    operations: ['join', 'filter', 'count', 'divide'],
    fragment_ids: ['frag_mtd_dates', 'frag_filtered_users_org', 'frag_testdrive_act_grp_strict', 'frag_testdrive_lead_grp_strict', 'frag_testdrive_conversion_ratio_select'],
    source_sql_id: 'src_fs31', verified: true,
  },
  {
    pattern_id: 'pat_testdrive_count_leadmatch', name: '시승건수(당월활동실적/시승완료)',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 시승완료 건수(lead 매칭 기준, 시승 후보 활동에 연결된 lead만)를 구한다.',
    intent: ['count'], metrics: ['시승건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_CRM_ACT_TYPE'],
    operations: ['join', 'filter', 'count'],
    fragment_ids: ['frag_mtd_dates', 'frag_filtered_users_org', 'frag_testdrive_act_grp_lenient', 'frag_testdrive_lead_grp_lenient', 'frag_testdrive_leadmatch_select'],
    source_sql_id: 'src_fs32', verified: true,
  },
  {
    pattern_id: 'pat_testdrive_count_form', name: '시승건수(당월활동실적/시승취소건 제외)',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 시승 활동 건수(시승취소만 제외, actual_cnt 합계 기준)를 구한다.',
    intent: ['count'], metrics: ['시승건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_CRM_ACT_TYPE'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_mtd_dates', 'frag_filtered_users_org', 'frag_testdrive_act_grp_lenient', 'frag_testdrive_lead_grp_lenient', 'frag_testdrive_form_select'],
    source_sql_id: 'src_fs33', verified: true,
  },
  {
    pattern_id: 'pat_testdrive_count_total_leaddistinct', name: '시승건수(당월전체실적, leadDistinct)',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 시승완료 건수를 영업기회(lead_key) 1건 기준으로 구한다(당월전체실적, 활동유형 필터 없음).',
    intent: ['count'], metrics: ['시승건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'count'],
    fragment_ids: ['frag_mtd_dates', 'frag_filtered_users_org', 'frag_lead_set', 'frag_testdrive_total_leaddistinct_select'],
    source_sql_id: 'src_fs34', verified: true,
  },
  {
    pattern_id: 'pat_testdrive_count_total_ac', name: '시승건수(당월전체실적, actual_cnt 기준)',
    description: '특정 딜러(선택 시 브랜드/전시장/부서까지)의 이번달 시승완료 건수를 actual_cnt 합계 기준으로 구한다(당월전체실적, 활동유형 필터 없음).',
    intent: ['count'], metrics: ['시승건수'], dimensions: ['딜러', '월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_mtd_dates', 'frag_filtered_users_org', 'frag_lead_set', 'frag_testdrive_total_ac_select'],
    source_sql_id: 'src_fs35', verified: true,
  },
  // ---- fs36~fs40: 1-2시트 신규 — 활동목표/기회전환률/기회진척률/계약전환률/계약진행률(조직별 목록) ----
  {
    pattern_id: 'pat_activity_target_list_by_org', name: '활동 목표 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 이번달 활동 목표를 나눠서 보여준다.',
    intent: ['breakdown'], metrics: ['활동목표'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_CRM_TARGET_D', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER'],
    operations: ['join', 'filter', 'group_by', 'sum'],
    fragment_ids: ['frag_activity_target_list_select'],
    source_sql_id: 'src_fs36', verified: true,
  },
  {
    pattern_id: 'pat_activity_lead_conversion_list_by_org', name: '기회 전환률 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 활동 대비 영업기회 전환율을 나눠서 보여준다.',
    intent: ['breakdown', 'ratio', 'conversion'], metrics: ['기회전환률'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'group_by', 'ratio', 'full_outer_join'],
    fragment_ids: ['frag_conv_org_lead', 'frag_conv_org_ac', 'frag_conv_org_select'],
    source_sql_id: 'src_fs37', verified: true,
  },
  {
    pattern_id: 'pat_lead_progress_list_by_org', name: '기회 진척률 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 영업기회 실적 대비 목표 진척률을 나눠서 보여준다.',
    intent: ['breakdown', 'ratio'], metrics: ['기회진척률'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::FCT_CRM_TARGET_M', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'group_by', 'ratio', 'full_outer_join'],
    fragment_ids: ['frag_lead_progress_org_actual', 'frag_lead_progress_org_target', 'frag_lead_progress_org_select'],
    source_sql_id: 'src_fs38', verified: true,
  },
  {
    pattern_id: 'pat_contract_conversion_list_by_org', name: '계약 전환률 목록(딜러/부서/SC/유형별)',
    description: '딜러/그룹/부서/SC/활동유형카테고리별로 영업기회 대비 계약 전환율을 나눠서 보여준다.',
    intent: ['breakdown', 'ratio', 'conversion'], metrics: ['계약전환률'], dimensions: ['딜러', '그룹', '부서', 'SC', '활동유형카테고리'],
    required_tables: ['KPI_W::FCT_CONTRACT_KTWS', 'KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER'],
    operations: ['join', 'filter', 'group_by', 'ratio', 'full_outer_join'],
    fragment_ids: ['frag_elig_user_org', 'frag_cntrct_conv_org_lead', 'frag_cntrct_conv_org_cntrct', 'frag_cntrct_conv_org_select'],
    source_sql_id: 'src_fs39', verified: true,
  },
  {
    pattern_id: 'pat_contract_progress_list_by_org', name: '계약 진행률 목록(딜러/부서/SC별)',
    description: '딜러/그룹/부서/SC별로 계약 실적 대비 목표 진행률을 나눠서 보여준다(SC 소계 레벨, 활동유형 구분 없음).',
    intent: ['breakdown', 'ratio'], metrics: ['계약진행률'], dimensions: ['딜러', '그룹', '부서', 'SC'],
    required_tables: ['KPI_W::FCT_CONTRACT_KTWS', 'KPI_W::FCT_CRM_TARGET_M', 'KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER'],
    operations: ['join', 'filter', 'group_by', 'ratio', 'full_outer_join'],
    fragment_ids: ['frag_elig_user_org', 'frag_cntrct_progress_org_cntrct', 'frag_cntrct_progress_org_tgt', 'frag_cntrct_progress_org_select'],
    source_sql_id: 'src_fs40', verified: true,
  },
  // ---- fs41~fs47: 1-3시트 신규 — 근무일(전부 신규) + SC현황 활동/기회전환(딜러 슬라이서 없음) ----
  {
    pattern_id: 'pat_working_day_progress', name: '근무일 진행률',
    description: '이번달 근무일(공휴일 제외) 중 오늘까지 지난 비율을 구한다.',
    intent: ['ratio'], metrics: ['근무일진행률'], dimensions: ['월'],
    required_tables: ['KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['filter', 'sum', 'divide'],
    fragment_ids: ['frag_working_day_progress_select'],
    source_sql_id: 'src_fs41', verified: true,
  },
  {
    pattern_id: 'pat_working_day_pass_count', name: '진행 근무일수',
    description: '이번달 근무일 중 오늘까지 지난 일수를 구한다.',
    intent: ['count'], metrics: ['진행근무일수'], dimensions: ['월'],
    required_tables: ['KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['filter', 'sum'],
    fragment_ids: ['frag_working_day_pass_select'],
    source_sql_id: 'src_fs42', verified: true,
  },
  {
    pattern_id: 'pat_working_day_total_count', name: '총 근무일수',
    description: '이번달 전체 근무일수(공휴일 제외)를 구한다.',
    intent: ['count'], metrics: ['총근무일수'], dimensions: ['월'],
    required_tables: ['KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['filter', 'sum'],
    fragment_ids: ['frag_working_day_total_select'],
    source_sql_id: 'src_fs43', verified: true,
  },
  {
    pattern_id: 'pat_sc_activity_count_all', name: 'SC현황 활동수(전체)',
    description: '전체 SC의 이번달 활동 건수 합계를 구한다(특정 딜러로 좁히지 않은 전사 합계).',
    intent: ['count'], metrics: ['활동건수'], dimensions: ['월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_sc_activity_count_select'],
    source_sql_id: 'src_fs44', verified: true,
  },
  {
    pattern_id: 'pat_sc_activity_target_all', name: 'SC현황 활동 당월 목표(전체)',
    description: '전체 SC의 이번달 활동 목표 합계를 구한다(전사 합계).',
    intent: ['count'], metrics: ['활동목표'], dimensions: ['월'],
    required_tables: ['KPI_W::FCT_CRM_TARGET_D', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER'],
    operations: ['join', 'filter', 'sum'],
    fragment_ids: ['frag_sc_activity_target_select'],
    source_sql_id: 'src_fs45', verified: true,
  },
  {
    pattern_id: 'pat_sc_activity_progress_all', name: 'SC현황 활동 진행률(전체)',
    description: '전체 SC의 이번달 활동 실적 대비 목표 진행률(%)을 구한다(전사 합계).',
    intent: ['ratio'], metrics: ['활동진행률'], dimensions: ['월'],
    required_tables: ['KPI_W::FCT_ACTIVITY_v2', 'KPI_W::FCT_CRM_TARGET_D', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CALENDAR_KTWS', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER'],
    operations: ['join', 'filter', 'sum', 'divide'],
    fragment_ids: ['frag_sc_act_actual_cte', 'frag_sc_act_target_cte', 'frag_sc_activity_progress_select'],
    source_sql_id: 'src_fs46', verified: true,
  },
  {
    pattern_id: 'pat_sc_lead_conversion_all', name: 'SC현황 활동기회전환(전체)',
    description: '전체 SC 기준 이번달 활동 대비 영업기회 전환율(%)을 구한다(전사 합계).',
    intent: ['ratio', 'conversion'], metrics: ['활동기회전환율'], dimensions: ['월'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_CRM_ACT_TYPE', 'KPI_W::DIM_CRM_ACT_TYPE_ORDER', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_MNG_DEALER', 'KPI_W::DIM_CALENDAR_KTWS'],
    operations: ['join', 'filter', 'count', 'divide'],
    fragment_ids: ['frag_sc_lead_actual_cte', 'frag_sc_act_actual_cte', 'frag_sc_lead_conversion_select'],
    source_sql_id: 'src_fs47', verified: true,
  },
  {
    pattern_id: 'pat_lead_detail_list', name: '영업기회 목록(리드 상세)',
    description: 'SC/고객명/등록일/관심도/시승요청일/시승일/계약일/출고일/최근활동일자/관심차종/접수유형을 리드 1건당 1행으로 나열한다.',
    intent: ['list'], metrics: [], dimensions: ['SC', '고객', '등록일'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::FCT_ACTIVITY_v2', 'KPI_W::DIM_VEHIC_SPEC_VAR'],
    operations: ['join', 'filter', 'subquery'],
    fragment_ids: ['frag_lead_detail_list_select'],
    source_sql_id: 'src_fs48', verified: true,
  },
  {
    pattern_id: 'pat_hboard_meeting_list', name: '핫보드 미팅 상세 목록',
    description: '이번년도 핫보드(HOT보드) 회의 미팅을 1건당 1행으로 나열한다(회차/미팅일자/상태/팀/SC/상담자/관심차종 등).',
    intent: ['list'], metrics: [], dimensions: ['SC', '팀', '미팅일자'],
    required_tables: ['KPI_W::FCT_HBOARD_MEETING', 'KPI_W::DIM_MNG_USER', 'KPI_W::DIM_VEHIC_SPEC_VAR'],
    operations: ['join', 'filter'],
    fragment_ids: ['frag_hboard_meeting_list_select'],
    source_sql_id: 'src_fs49', verified: true,
  },
  // ---- fs50~fs51: 7시트 SC 출고 매트릭스 (복잡도 높음, 단일 fragment) ----
  {
    pattern_id: 'pat_sc_group_count_matrix', name: 'SC 그룹 카운트(딜러/전시장/팀별 출고평균대수·누적취소율 대상 인원수)',
    description: '딜러/전시장/팀별로 출고평균대수·누적취소율 실적이 있는(등급판정 대상) SC 인원수를 구한다.',
    intent: ['breakdown', 'count'], metrics: ['SC인원수'], dimensions: ['딜러', '전시장', '팀'],
    required_tables: ['KPI_W::DIM_MNG_USER', 'KPI_W::FCT_SC_GROUP_RULE', 'KPI_W::FCT_CONTRACT_KTWS'],
    operations: ['join', 'filter', 'group_by', 'count'],
    fragment_ids: ['frag_sc_group_count_matrix_select'],
    source_sql_id: 'src_fs50', verified: true,
  },
  {
    pattern_id: 'pat_sc_delivery_matrix', name: 'SC별 출고평균대수·누적취소율·연누적출고·PMA 상세표',
    description: 'SC별 월평균 출고대수, 누적취소율, 연누적(YTD) 출고, PMA IN/OUT 건수와 비중을 한 행씩 보여준다(전체 합계 행 포함).',
    intent: ['list'], metrics: ['월평균출고', '누적취소율', '연누적출고', 'PMA IN', 'PMA OUT'], dimensions: ['SC'],
    required_tables: ['KPI_W::DIM_MNG_USER', 'KPI_W::FCT_SC_GROUP_RULE', 'KPI_W::FCT_CONTRACT_KTWS'],
    operations: ['join', 'filter', 'group_by', 'sum', 'divide', 'union_all'],
    fragment_ids: ['frag_sc_delivery_matrix_select'],
    source_sql_id: 'src_fs51', verified: true,
  },
  // ---- 신규 파생(2026-07-22): GOLD 원본 없음 — frag_sc_delivery_matrix_select와 같은
  // sales_period_monthly_avg_scSelected 정의를 SC 단위 대신 BRAND 단위로 재사용 ----
  {
    pattern_id: 'pat_delivery_avg_by_dimension', name: '차원별 출고 평균대수(딜러/브랜드/전시장/부서/SC)',
    description: '딜러/브랜드/전시장/부서/SC 중 요청된 기준으로 SC 1인당 월평균 출고대수(최근 6개월, 실적 있는 달만 평균)를 구한다. 딜러별/브랜드별/전시장별/부서별/SC별 중 어떤 걸 물어도 같은 패턴이 처리한다(GROUP BY 축만 dimension 카탈로그로 결정론적 치환).',
    intent: ['avg', 'breakdown'], metrics: ['출고평균대수'], dimensions: ['딜러', '브랜드', '전시장', '부서', 'SC'],
    required_tables: ['KPI_W::DIM_MNG_USER', 'KPI_W::FCT_CONTRACT_KTWS'],
    operations: ['join', 'filter', 'group_by', 'avg', 'divide'],
    fragment_ids: ['frag_sc_monthly_sales_by_dim', 'frag_delivery_avg_by_dim_select'],
    source_sql_id: null, verified: false,
  },
  {
    pattern_id: 'pat_lead_journey_chip_detail', name: '리드 여정 칩보드+상세(구간별)',
    description: '이번달 클로즈된 리드를 구간(한달이내출고/계약/시승/상담)별로 나눠 칩보드용 라벨과 함께 보여주고, 동시에 상담→시승→계약→출고 4단계 통과 여부(Y/N)와 단계별 날짜를 리드별로 함께 싣는다.',
    intent: ['list'], metrics: ['리드여정상세'], dimensions: ['구간', '딜러', '전시장', '팀', 'SC', '시승여부'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::FCT_ACTIVITY_v2'],
    operations: ['join', 'filter', 'group_by', 'union_all', 'case_when'],
    fragment_ids: [
      'frag_lead_journey_base', 'frag_lead_journey_td_metrics', 'frag_lead_journey_td_latest', 'frag_lead_journey_consult',
      'frag_lead_journey_td_label', 'frag_lead_journey_flag',
      'frag_lead_journey_seg_ship', 'frag_lead_journey_seg_contract', 'frag_lead_journey_seg_td', 'frag_lead_journey_seg_consult',
      'frag_lead_journey_seg_union', 'frag_lead_journey_chip_select',
    ],
    source_sql_id: 'src_fs52', verified: true,
  },
  {
    pattern_id: 'pat_lead_journey_funnel_by_td', name: '리드 여정 퍼널(시승여부별 단계 카운트)',
    description: '이번달 클로즈된 리드를 시승여부(Y/N)로 나눠, 각각 상담→시승→계약→출고 4단계를 통과한 리드 수를 센다 — 역삼각형 퍼널 2개(시승O/시승X)를 그리는 데이터.',
    intent: ['breakdown'], metrics: ['상담', '시승', '계약', '출고'], dimensions: ['시승여부'],
    required_tables: ['KPI_W::FCT_LEAD', 'KPI_W::DIM_MNG_USER', 'KPI_W::FCT_ACTIVITY_v2'],
    operations: ['join', 'filter', 'group_by', 'sum', 'case_when'],
    fragment_ids: [
      'frag_lead_journey_base', 'frag_lead_journey_td_metrics', 'frag_lead_journey_td_latest', 'frag_lead_journey_consult',
      'frag_lead_journey_td_flag_simple', 'frag_lead_journey_funnel_select',
    ],
    source_sql_id: 'src_fs53', verified: true,
  },
  {
    pattern_id: 'pat_dealer_ytd_shipment_matrix', name: '딜러/전시장/부서/SC/PMA구분별 연누적 출고',
    description: '연초~기준월말(YTD) 출고(미취소) 건수를 딜러>전시장>부서>SC>PMA구분(IN/OUT/etc) 계층으로 센다. "딜러사별 출고(실적/현황/평균대수)" 같은 딜러 단위 출고 질문의 기준 소스 — 등급 필터·재직 필터 없음(GOLD 원본 명시 사항).',
    intent: ['breakdown'], metrics: ['연누적출고'], dimensions: ['딜러', '전시장', '부서', 'SC', 'PMA구분'],
    required_tables: ['KPI_W::DIM_MNG_USER', 'KPI_W::FCT_CONTRACT_KTWS', 'KPI_W::DIM_PMA_ORDER'],
    operations: ['join', 'filter', 'group_by', 'count_distinct'],
    fragment_ids: ['frag_dealer_ytd_ship_scope', 'frag_dealer_ytd_ship_select'],
    source_sql_id: 'src_fs54', verified: true,
  },
]

// Embeddable blurb — description + intent + metrics + operations only, NEVER the SQL/fragment
// bodies (those live behind fragment_ids, resolved by ID in Stage 4, not searched).
export function patternText(p) {
  return `이름: ${p.name}\n설명: ${p.description}\n의도: ${p.intent.join(', ')}\n측정값: ${p.metrics.join(', ')}\n차원: ${p.dimensions.join(', ')}\n연산: ${p.operations.join(', ')}`
}
