/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedOrgChartRouteImport } from './routes/_authenticated/orgChart'
import { Route as AuthenticatedModelDeploymentRouteImport } from './routes/_authenticated/modelDeployment'
import { Route as AuthenticatedDataAgentRouteImport } from './routes/_authenticated/dataAgent'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedCompanyInfoRouteImport } from './routes/_authenticated/companyInfo'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAiAgentIndexRouteImport } from './routes/_authenticated/aiAgent/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgChartRoute = AuthenticatedOrgChartRouteImport.update({
  id: '/orgChart',
  path: '/orgChart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelDeploymentRoute =
  AuthenticatedModelDeploymentRouteImport.update({
    id: '/modelDeployment',
    path: '/modelDeployment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataAgentRoute = AuthenticatedDataAgentRouteImport.update({
  id: '/dataAgent',
  path: '/dataAgent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyInfoRoute =
  AuthenticatedCompanyInfoRouteImport.update({
    id: '/companyInfo',
    path: '/companyInfo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAgentIndexRoute =
  AuthenticatedAiAgentIndexRouteImport.update({
    id: '/aiAgent/',
    path: '/aiAgent/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/companyInfo': typeof AuthenticatedCompanyInfoRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dataAgent': typeof AuthenticatedDataAgentRoute
  '/modelDeployment': typeof AuthenticatedModelDeploymentRoute
  '/orgChart': typeof AuthenticatedOrgChartRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/users': typeof AuthenticatedUsersRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/aiAgent': typeof AuthenticatedAiAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/companyInfo': typeof AuthenticatedCompanyInfoRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dataAgent': typeof AuthenticatedDataAgentRoute
  '/modelDeployment': typeof AuthenticatedModelDeploymentRoute
  '/orgChart': typeof AuthenticatedOrgChartRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/users': typeof AuthenticatedUsersRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/aiAgent': typeof AuthenticatedAiAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/companyInfo': typeof AuthenticatedCompanyInfoRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dataAgent': typeof AuthenticatedDataAgentRoute
  '/_authenticated/modelDeployment': typeof AuthenticatedModelDeploymentRoute
  '/_authenticated/orgChart': typeof AuthenticatedOrgChartRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/_authenticated/aiAgent/': typeof AuthenticatedAiAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/branches'
    | '/companyInfo'
    | '/copilot'
    | '/dataAgent'
    | '/modelDeployment'
    | '/orgChart'
    | '/usage'
    | '/users'
    | '/workspaces'
    | '/aiAgent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/branches'
    | '/companyInfo'
    | '/copilot'
    | '/dataAgent'
    | '/modelDeployment'
    | '/orgChart'
    | '/usage'
    | '/users'
    | '/workspaces'
    | '/aiAgent'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/branches'
    | '/_authenticated/companyInfo'
    | '/_authenticated/copilot'
    | '/_authenticated/dataAgent'
    | '/_authenticated/modelDeployment'
    | '/_authenticated/orgChart'
    | '/_authenticated/usage'
    | '/_authenticated/users'
    | '/_authenticated/workspaces'
    | '/_authenticated/aiAgent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgChart': {
      id: '/_authenticated/orgChart'
      path: '/orgChart'
      fullPath: '/orgChart'
      preLoaderRoute: typeof AuthenticatedOrgChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelDeployment': {
      id: '/_authenticated/modelDeployment'
      path: '/modelDeployment'
      fullPath: '/modelDeployment'
      preLoaderRoute: typeof AuthenticatedModelDeploymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dataAgent': {
      id: '/_authenticated/dataAgent'
      path: '/dataAgent'
      fullPath: '/dataAgent'
      preLoaderRoute: typeof AuthenticatedDataAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companyInfo': {
      id: '/_authenticated/companyInfo'
      path: '/companyInfo'
      fullPath: '/companyInfo'
      preLoaderRoute: typeof AuthenticatedCompanyInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aiAgent/': {
      id: '/_authenticated/aiAgent/'
      path: '/aiAgent'
      fullPath: '/aiAgent'
      preLoaderRoute: typeof AuthenticatedAiAgentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCompanyInfoRoute: typeof AuthenticatedCompanyInfoRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDataAgentRoute: typeof AuthenticatedDataAgentRoute
  AuthenticatedModelDeploymentRoute: typeof AuthenticatedModelDeploymentRoute
  AuthenticatedOrgChartRoute: typeof AuthenticatedOrgChartRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedAiAgentIndexRoute: typeof AuthenticatedAiAgentIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCompanyInfoRoute: AuthenticatedCompanyInfoRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDataAgentRoute: AuthenticatedDataAgentRoute,
  AuthenticatedModelDeploymentRoute: AuthenticatedModelDeploymentRoute,
  AuthenticatedOrgChartRoute: AuthenticatedOrgChartRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedAiAgentIndexRoute: AuthenticatedAiAgentIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
