-- =====================================================================
-- Ai365 Admin Center  |  PostgreSQL DDL  (dbo + agent 스키마)
-- =====================================================================
-- 스키마 2개를 같은 데이터베이스 안에 나눠 둔다.
--   dbo    어드민이 쓴다   - 딜러사 · 사용자 · 모델 · 프롬프트
--   agent  에이전트가 쓴다 - 대화 이력 · 토큰 사용량
--
-- 나누는 기준은 "누가 INSERT 하느냐"다. 읽기는 서로 자유롭게 한다.
--
-- 어드민 메뉴와 테이블
--   회사 정보     -> dbo."CompanyInfo_master"
--   사용자        -> dbo."User_master" / dbo."User_AD_master"
--   모델 배포     -> dbo."Model_master", dbo."CompanyInfo_ModelDeployment"
--   프롬프트 설정 -> dbo."SystemPrompt_Configuration"
--   사용량        -> agent."TokenUsage_log"
--
-- 딜러사(Company)는 단일 계층이다. Branch / Workspace 개념은 없고,
-- 활성/비활성은 CompanyInfo_master.is_active 로만 판단한다.
--
-- ※ 이 파일은 운영 중이던 로컬 DB 에서 pg_dump 로 복원한 것이다.
--   이전 버전(schema_postgres_core.sql / _agent.sql / _link.sql)은 인코딩이
--   깨지면서 컬럼 정의와 문자열 종료 따옴표가 사라져 빈 DB 에서 initdb 가
--   실패했다. 세 파일을 이 한 파일로 합쳐 대체한다.
--   딜러사 ↔ scope 연결 데이터는 050_admin_link.sql 이 이어서 채운다.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid() (PG13+ 는 내장)


--
-- Name: agent; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS agent;


--
-- Name: dbo; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS dbo;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: agent; Owner: -
--

CREATE FUNCTION agent.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: dbo; Owner: -
--

CREATE FUNCTION dbo.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Chat_message; Type: TABLE; Schema: agent; Owner: -
--

CREATE TABLE agent."Chat_message" (
    message_id uuid DEFAULT gen_random_uuid() NOT NULL,
    session_id uuid NOT NULL,
    seq integer NOT NULL,
    role character varying(20) NOT NULL,
    content text NOT NULL,
    generated_sql text,
    chart_spec jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_chat_role CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying])::text[])))
);


--
-- Name: COLUMN "Chat_message".chart_spec; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON COLUMN agent."Chat_message".chart_spec IS '차트 설정만. 조회 결과는 저장하지 않는다';


--
-- Name: Chat_session; Type: TABLE; Schema: agent; Owner: -
--

CREATE TABLE agent."Chat_session" (
    session_id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_info_id uuid NOT NULL,
    user_email character varying(255) NOT NULL,
    title character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);


--
-- Name: TABLE "Chat_session"; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON TABLE agent."Chat_session" IS '대화 스레드. 딜러사와 이메일로 격리된다';


--
-- Name: COLUMN "Chat_session".user_email; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON COLUMN agent."Chat_session".user_email IS 'FK 를 걸지 않는다 - 계정이 삭제돼도 대화는 남아야 한다';


--
-- Name: TokenUsage_log; Type: TABLE; Schema: agent; Owner: -
--

CREATE TABLE agent."TokenUsage_log" (
    id bigint NOT NULL,
    company_info_id uuid NOT NULL,
    user_email character varying(255),
    session_id uuid,
    message_id uuid,
    agent_type character varying(20),
    model_id uuid,
    input_tokens integer DEFAULT 0 NOT NULL,
    output_tokens integer DEFAULT 0 NOT NULL,
    latency_ms integer,
    succeeded boolean DEFAULT true NOT NULL,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE "TokenUsage_log"; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON TABLE agent."TokenUsage_log" IS '토큰 사용량. 딜러사별 리포트의 원천이며 호출 한 건이 한 행이다';


--
-- Name: COLUMN "TokenUsage_log".user_email; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON COLUMN agent."TokenUsage_log".user_email IS '사용자 이메일. FK 를 걸지 않는다 - 계정이 지워져도 지난 사용량은 남아야 한다';


--
-- Name: COLUMN "TokenUsage_log".message_id; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON COLUMN agent."TokenUsage_log".message_id IS '어느 답변을 만들다 쓴 토큰인가. 답변 1건에 여러 행이 달린다';


--
-- Name: COLUMN "TokenUsage_log".agent_type; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON COLUMN agent."TokenUsage_log".agent_type IS '용도. 키 단위 집계로는 얻을 수 없는 분해축이라 여기에 남긴다';


--
-- Name: TokenUsage_log_id_seq; Type: SEQUENCE; Schema: agent; Owner: -
--

ALTER TABLE agent."TokenUsage_log" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME agent."TokenUsage_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CompanyInfo_master; Type: TABLE; Schema: dbo; Owner: -
--

CREATE TABLE dbo."CompanyInfo_master" (
    company_info_id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_info_name character varying(255) NOT NULL,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);


--
-- Name: TABLE "CompanyInfo_master"; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON TABLE dbo."CompanyInfo_master" IS '딜러사 마스터. 모델키/사용자 격리의 유일한 기준';


--
-- Name: COLUMN "CompanyInfo_master".company_info_name; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON COLUMN dbo."CompanyInfo_master".company_info_name IS '딜러사명. 에이전트가 쿼리 조건으로 쓸 값이라 데이터 원본의 딜러사 값과 글자가 일치해야 한다';


--
-- Name: COLUMN "CompanyInfo_master".is_active; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON COLUMN dbo."CompanyInfo_master".is_active IS '구 Branch 메뉴의 활성/비활성 토글. 회사 정보 메뉴에서 직접 제어';


--
-- Name: v_token_usage_by_user; Type: VIEW; Schema: agent; Owner: -
--

CREATE VIEW agent.v_token_usage_by_user AS
 SELECT (t.created_at)::date AS usage_date,
    t.company_info_id,
    c.company_info_name,
    COALESCE(t.user_email, '(시스템)'::character varying) AS user_email,
    count(*) AS request_count,
    count(*) FILTER (WHERE (NOT t.succeeded)) AS failed_count,
    sum(t.input_tokens) AS input_tokens,
    sum(t.output_tokens) AS output_tokens,
    sum((t.input_tokens + t.output_tokens)) AS total_tokens,
    (avg(t.latency_ms))::integer AS avg_latency_ms,
    max(t.created_at) AS last_used_at
   FROM (agent."TokenUsage_log" t
     JOIN dbo."CompanyInfo_master" c ON ((c.company_info_id = t.company_info_id)))
  GROUP BY ((t.created_at)::date), t.company_info_id, c.company_info_name, COALESCE(t.user_email, '(시스템)'::character varying);


--
-- Name: VIEW v_token_usage_by_user; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON VIEW agent.v_token_usage_by_user IS '날짜 x 딜러사 x 이메일 사용량. usage_date 로 기간을 거른 뒤 다시 합쳐 쓴다';


--
-- Name: v_token_usage_daily; Type: VIEW; Schema: agent; Owner: -
--

CREATE VIEW agent.v_token_usage_daily AS
 SELECT (t.created_at)::date AS usage_date,
    t.company_info_id,
    c.company_info_name,
    count(*) AS request_count,
    sum((t.input_tokens + t.output_tokens)) AS total_tokens
   FROM (agent."TokenUsage_log" t
     JOIN dbo."CompanyInfo_master" c ON ((c.company_info_id = t.company_info_id)))
  GROUP BY ((t.created_at)::date), t.company_info_id, c.company_info_name;


--
-- Name: CompanyInfo_ModelDeployment; Type: TABLE; Schema: dbo; Owner: -
--

CREATE TABLE dbo."CompanyInfo_ModelDeployment" (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_info_id uuid NOT NULL,
    model_id uuid NOT NULL,
    agent_type character varying(20) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT ck_deploy_agent_type CHECK (((agent_type)::text = ANY ((ARRAY['main'::character varying, 'sql'::character varying, 'sql_2'::character varying, 'rag'::character varying, 'powerbi'::character varying, 'chart'::character varying])::text[])))
);


--
-- Name: Model_master; Type: TABLE; Schema: dbo; Owner: -
--

CREATE TABLE dbo."Model_master" (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    display_name character varying(100) NOT NULL,
    provider character varying(30) DEFAULT 'bedrock'::character varying NOT NULL,
    model_kind character varying(20) DEFAULT 'llm'::character varying NOT NULL,
    model_id character varying(200) NOT NULL,
    api_version character varying(50),
    max_token integer,
    temperature numeric(3,2),
    top_p numeric(3,2),
    top_k smallint,
    reasoning_effort character varying(20),
    embedding_model character varying(200),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT ck_model_kind CHECK (((model_kind)::text = ANY ((ARRAY['llm'::character varying, 'embedding'::character varying])::text[]))),
    CONSTRAINT ck_model_provider CHECK (((provider)::text = ANY ((ARRAY['bedrock'::character varying, 'azure_openai'::character varying, 'openai'::character varying, 'vertex'::character varying])::text[])))
);


--
-- Name: TABLE "Model_master"; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON TABLE dbo."Model_master" IS '모델 스펙 카탈로그. 여러 딜러사가 같은 행을 공유하고 키만 각자 다른 것을 붙여 쓴다';


--
-- Name: COLUMN "Model_master".model_id; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON COLUMN dbo."Model_master".model_id IS 'provider 별 호출 식별자. bedrock 예: anthropic.claude-sonnet-4-5-20250929-v1:0';


--
-- Name: COLUMN "Model_master".temperature; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON COLUMN dbo."Model_master".temperature IS '0.7 같은 소수를 담아야 하므로 numeric. smallint 로는 저장할 수 없다';


--
-- Name: ScopeCompany_map; Type: TABLE; Schema: dbo; Owner: -
--

CREATE TABLE dbo."ScopeCompany_map" (
    scope_key text NOT NULL,
    company_info_id uuid NOT NULL
);


--
-- Name: TABLE "ScopeCompany_map"; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON TABLE dbo."ScopeCompany_map" IS 'scope_key <-> company_info_id. 에이전트와 어드민이 같은 딜러사를 가리키게 하는 유일한 연결';


--
-- Name: SystemPrompt_Configuration; Type: TABLE; Schema: dbo; Owner: -
--

CREATE TABLE dbo."SystemPrompt_Configuration" (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    category character varying(20) NOT NULL,
    name character varying(200) NOT NULL,
    file_name character varying(255),
    file_type character varying(10) DEFAULT 'yaml'::character varying NOT NULL,
    value text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT ck_prompt_category CHECK (((category)::text = ANY ((ARRAY['semantic'::character varying, 'ontology'::character varying, 'metrics'::character varying])::text[]))),
    CONSTRAINT ck_prompt_file_type CHECK (((file_type)::text = ANY ((ARRAY['yaml'::character varying, 'md'::character varying])::text[])))
);


--
-- Name: TABLE "SystemPrompt_Configuration"; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON TABLE dbo."SystemPrompt_Configuration" IS '전역 프롬프트. 카테고리(semantic/ontology/metrics) 별로 여러 파일을 갖는다';


--
-- Name: COLUMN "SystemPrompt_Configuration".value; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON COLUMN dbo."SystemPrompt_Configuration".value IS 'yaml/md 파일의 텍스트 본문. 파일은 스토리지에 두지 않고 본문만 저장한다';


--
-- Name: User_AD_master; Type: TABLE; Schema: dbo; Owner: -
--

CREATE TABLE dbo."User_AD_master" (
    user_id uuid NOT NULL,
    user_name character varying(100) NOT NULL,
    user_email character varying(255) NOT NULL,
    user_role character varying(20) DEFAULT 'user'::character varying NOT NULL,
    user_access character varying(255),
    user_department character varying(100),
    user_avatar text,
    default_company uuid NOT NULL,
    default_language character varying(50) DEFAULT 'en'::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT ck_user_ad_role CHECK (((user_role)::text = ANY ((ARRAY['admin'::character varying, 'user'::character varying, 'viewer'::character varying])::text[])))
);


--
-- Name: User_master; Type: TABLE; Schema: dbo; Owner: -
--

CREATE TABLE dbo."User_master" (
    user_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_name character varying(100) NOT NULL,
    user_email character varying(255) NOT NULL,
    user_password character varying(255) NOT NULL,
    user_role character varying(20) DEFAULT 'user'::character varying NOT NULL,
    user_access character varying(255),
    user_department character varying(100),
    default_company uuid NOT NULL,
    default_language character varying(50) DEFAULT 'en'::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT ck_user_role CHECK (((user_role)::text = ANY ((ARRAY['admin'::character varying, 'user'::character varying, 'viewer'::character varying])::text[])))
);


--
-- Name: COLUMN "User_master".user_role; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON COLUMN dbo."User_master".user_role IS 'admin | user | viewer. 각 권한이 무엇을 허용하는지는 에이전트 백엔드가 판단한다';


--
-- Name: COLUMN "User_master".default_company; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON COLUMN dbo."User_master".default_company IS '이 컬럼 하나가 접근 범위 전체. 구 User_Assignment 를 대체한다';


--
-- Name: v_company; Type: VIEW; Schema: dbo; Owner: -
--

CREATE VIEW dbo.v_company AS
 SELECT company_info_id,
    company_info_name,
    description
   FROM dbo."CompanyInfo_master"
  WHERE (is_active AND (deleted_at IS NULL));


--
-- Name: v_company_agent_config; Type: VIEW; Schema: dbo; Owner: -
--

CREATE VIEW dbo.v_company_agent_config AS
 SELECT c.company_info_id,
    c.company_info_name,
    d.agent_type,
    m.display_name,
    m.provider,
    m.model_kind,
    m.model_id,
    m.api_version,
    m.max_token,
    m.temperature,
    m.top_p,
    m.top_k,
    m.reasoning_effort,
    m.embedding_model
   FROM ((dbo."CompanyInfo_master" c
     JOIN dbo."CompanyInfo_ModelDeployment" d ON ((d.company_info_id = c.company_info_id)))
     JOIN dbo."Model_master" m ON (((m.id = d.model_id) AND m.is_active)))
  WHERE (c.is_active AND (c.deleted_at IS NULL));


--
-- Name: VIEW v_company_agent_config; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON VIEW dbo.v_company_agent_config IS '에이전트가 부팅 시 1회 조회. agent_type 별로 쓸 모델이 한 행씩';


--
-- Name: v_system_prompt; Type: VIEW; Schema: dbo; Owner: -
--

CREATE VIEW dbo.v_system_prompt AS
 SELECT id,
    category,
    name,
    file_name,
    file_type,
    value,
    updated_at
   FROM dbo."SystemPrompt_Configuration"
  WHERE is_active
  ORDER BY category, name;


--
-- Name: v_user_company; Type: VIEW; Schema: dbo; Owner: -
--

CREATE VIEW dbo.v_user_company AS
 SELECT u.user_id,
    lower((u.user_email)::text) AS user_email,
    u.user_name,
    u.user_role,
    u.user_department,
    u.default_language,
    'local'::character varying(10) AS provider,
    c.company_info_id,
    c.company_info_name
   FROM (dbo."User_master" u
     JOIN dbo."CompanyInfo_master" c ON ((c.company_info_id = u.default_company)))
  WHERE (u.is_active AND c.is_active AND (c.deleted_at IS NULL))
UNION ALL
 SELECT a.user_id,
    lower((a.user_email)::text) AS user_email,
    a.user_name,
    a.user_role,
    a.user_department,
    a.default_language,
    'ad'::character varying(10) AS provider,
    c.company_info_id,
    c.company_info_name
   FROM (dbo."User_AD_master" a
     JOIN dbo."CompanyInfo_master" c ON ((c.company_info_id = a.default_company)))
  WHERE (a.is_active AND c.is_active AND (c.deleted_at IS NULL));


--
-- Name: VIEW v_user_company; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON VIEW dbo.v_user_company IS '이메일 한 건으로 소속 딜러사명 + user_role. 이 값으로 무엇을 할지는 에이전트가 결정';


--
-- Name: Chat_message Chat_message_pkey; Type: CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."Chat_message"
    ADD CONSTRAINT "Chat_message_pkey" PRIMARY KEY (message_id);


--
-- Name: Chat_session Chat_session_pkey; Type: CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."Chat_session"
    ADD CONSTRAINT "Chat_session_pkey" PRIMARY KEY (session_id);


--
-- Name: TokenUsage_log TokenUsage_log_pkey; Type: CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."TokenUsage_log"
    ADD CONSTRAINT "TokenUsage_log_pkey" PRIMARY KEY (id);


--
-- Name: Chat_message uq_chat_seq; Type: CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."Chat_message"
    ADD CONSTRAINT uq_chat_seq UNIQUE (session_id, seq);


--
-- Name: CONSTRAINT uq_chat_seq ON "Chat_message"; Type: COMMENT; Schema: agent; Owner: -
--

COMMENT ON CONSTRAINT uq_chat_seq ON agent."Chat_message" IS '세션 내 순번 중복 차단. created_at 만으로는 같은 밀리초 두 건의 순서가 흔들린다';


--
-- Name: CompanyInfo_ModelDeployment CompanyInfo_ModelDeployment_pkey; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."CompanyInfo_ModelDeployment"
    ADD CONSTRAINT "CompanyInfo_ModelDeployment_pkey" PRIMARY KEY (id);


--
-- Name: CompanyInfo_master CompanyInfo_master_pkey; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."CompanyInfo_master"
    ADD CONSTRAINT "CompanyInfo_master_pkey" PRIMARY KEY (company_info_id);


--
-- Name: Model_master Model_master_pkey; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."Model_master"
    ADD CONSTRAINT "Model_master_pkey" PRIMARY KEY (id);


--
-- Name: ScopeCompany_map ScopeCompany_map_company_info_id_key; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."ScopeCompany_map"
    ADD CONSTRAINT "ScopeCompany_map_company_info_id_key" UNIQUE (company_info_id);


--
-- Name: ScopeCompany_map ScopeCompany_map_pkey; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."ScopeCompany_map"
    ADD CONSTRAINT "ScopeCompany_map_pkey" PRIMARY KEY (scope_key);


--
-- Name: SystemPrompt_Configuration SystemPrompt_Configuration_pkey; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."SystemPrompt_Configuration"
    ADD CONSTRAINT "SystemPrompt_Configuration_pkey" PRIMARY KEY (id);


--
-- Name: User_AD_master User_AD_master_pkey; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."User_AD_master"
    ADD CONSTRAINT "User_AD_master_pkey" PRIMARY KEY (user_id);


--
-- Name: User_master User_master_pkey; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."User_master"
    ADD CONSTRAINT "User_master_pkey" PRIMARY KEY (user_id);


--
-- Name: CompanyInfo_ModelDeployment uq_company_deployment; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."CompanyInfo_ModelDeployment"
    ADD CONSTRAINT uq_company_deployment UNIQUE (company_info_id, agent_type);


--
-- Name: CONSTRAINT uq_company_deployment ON "CompanyInfo_ModelDeployment"; Type: COMMENT; Schema: dbo; Owner: -
--

COMMENT ON CONSTRAINT uq_company_deployment ON dbo."CompanyInfo_ModelDeployment" IS '딜러사 x 용도 당 모델 1개. 중복 시 조용히 덮어써지는 사고를 DB 에서 차단';


--
-- Name: CompanyInfo_master uq_company_name; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."CompanyInfo_master"
    ADD CONSTRAINT uq_company_name UNIQUE (company_info_name);


--
-- Name: Model_master uq_model_display; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."Model_master"
    ADD CONSTRAINT uq_model_display UNIQUE (display_name);


--
-- Name: SystemPrompt_Configuration uq_prompt_name; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."SystemPrompt_Configuration"
    ADD CONSTRAINT uq_prompt_name UNIQUE (category, name);


--
-- Name: User_AD_master uq_user_ad_email; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."User_AD_master"
    ADD CONSTRAINT uq_user_ad_email UNIQUE (user_email);


--
-- Name: User_master uq_user_email; Type: CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."User_master"
    ADD CONSTRAINT uq_user_email UNIQUE (user_email);


--
-- Name: ix_chat_message_session; Type: INDEX; Schema: agent; Owner: -
--

CREATE INDEX ix_chat_message_session ON agent."Chat_message" USING btree (session_id, seq);


--
-- Name: ix_chat_session_owner; Type: INDEX; Schema: agent; Owner: -
--

CREATE INDEX ix_chat_session_owner ON agent."Chat_session" USING btree (company_info_id, user_email, created_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: ix_usage_company_time; Type: INDEX; Schema: agent; Owner: -
--

CREATE INDEX ix_usage_company_time ON agent."TokenUsage_log" USING btree (company_info_id, created_at DESC);


--
-- Name: ix_usage_company_user; Type: INDEX; Schema: agent; Owner: -
--

CREATE INDEX ix_usage_company_user ON agent."TokenUsage_log" USING btree (company_info_id, user_email, created_at DESC);


--
-- Name: ix_usage_time; Type: INDEX; Schema: agent; Owner: -
--

CREATE INDEX ix_usage_time ON agent."TokenUsage_log" USING btree (created_at DESC);


--
-- Name: ix_company_active; Type: INDEX; Schema: dbo; Owner: -
--

CREATE INDEX ix_company_active ON dbo."CompanyInfo_master" USING btree (is_active) WHERE (deleted_at IS NULL);


--
-- Name: ix_deploy_company; Type: INDEX; Schema: dbo; Owner: -
--

CREATE INDEX ix_deploy_company ON dbo."CompanyInfo_ModelDeployment" USING btree (company_info_id);


--
-- Name: ix_prompt_category; Type: INDEX; Schema: dbo; Owner: -
--

CREATE INDEX ix_prompt_category ON dbo."SystemPrompt_Configuration" USING btree (category) WHERE is_active;


--
-- Name: ix_user_ad_company; Type: INDEX; Schema: dbo; Owner: -
--

CREATE INDEX ix_user_ad_company ON dbo."User_AD_master" USING btree (default_company);


--
-- Name: ix_user_ad_email_lower; Type: INDEX; Schema: dbo; Owner: -
--

CREATE INDEX ix_user_ad_email_lower ON dbo."User_AD_master" USING btree (lower((user_email)::text));


--
-- Name: ix_user_company; Type: INDEX; Schema: dbo; Owner: -
--

CREATE INDEX ix_user_company ON dbo."User_master" USING btree (default_company);


--
-- Name: ix_user_email_lower; Type: INDEX; Schema: dbo; Owner: -
--

CREATE INDEX ix_user_email_lower ON dbo."User_master" USING btree (lower((user_email)::text));


--
-- Name: Chat_session trg_chat_session_updated; Type: TRIGGER; Schema: agent; Owner: -
--

CREATE TRIGGER trg_chat_session_updated BEFORE UPDATE ON agent."Chat_session" FOR EACH ROW EXECUTE FUNCTION agent.set_updated_at();


--
-- Name: CompanyInfo_master trg_company_updated; Type: TRIGGER; Schema: dbo; Owner: -
--

CREATE TRIGGER trg_company_updated BEFORE UPDATE ON dbo."CompanyInfo_master" FOR EACH ROW EXECUTE FUNCTION dbo.set_updated_at();


--
-- Name: CompanyInfo_ModelDeployment trg_deploy_updated; Type: TRIGGER; Schema: dbo; Owner: -
--

CREATE TRIGGER trg_deploy_updated BEFORE UPDATE ON dbo."CompanyInfo_ModelDeployment" FOR EACH ROW EXECUTE FUNCTION dbo.set_updated_at();


--
-- Name: Model_master trg_model_updated; Type: TRIGGER; Schema: dbo; Owner: -
--

CREATE TRIGGER trg_model_updated BEFORE UPDATE ON dbo."Model_master" FOR EACH ROW EXECUTE FUNCTION dbo.set_updated_at();


--
-- Name: SystemPrompt_Configuration trg_prompt_updated; Type: TRIGGER; Schema: dbo; Owner: -
--

CREATE TRIGGER trg_prompt_updated BEFORE UPDATE ON dbo."SystemPrompt_Configuration" FOR EACH ROW EXECUTE FUNCTION dbo.set_updated_at();


--
-- Name: User_AD_master trg_user_ad_updated; Type: TRIGGER; Schema: dbo; Owner: -
--

CREATE TRIGGER trg_user_ad_updated BEFORE UPDATE ON dbo."User_AD_master" FOR EACH ROW EXECUTE FUNCTION dbo.set_updated_at();


--
-- Name: User_master trg_user_updated; Type: TRIGGER; Schema: dbo; Owner: -
--

CREATE TRIGGER trg_user_updated BEFORE UPDATE ON dbo."User_master" FOR EACH ROW EXECUTE FUNCTION dbo.set_updated_at();


--
-- Name: Chat_message Chat_message_session_id_fkey; Type: FK CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."Chat_message"
    ADD CONSTRAINT "Chat_message_session_id_fkey" FOREIGN KEY (session_id) REFERENCES agent."Chat_session"(session_id) ON DELETE CASCADE;


--
-- Name: Chat_session Chat_session_company_info_id_fkey; Type: FK CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."Chat_session"
    ADD CONSTRAINT "Chat_session_company_info_id_fkey" FOREIGN KEY (company_info_id) REFERENCES dbo."CompanyInfo_master"(company_info_id) ON DELETE CASCADE;


--
-- Name: TokenUsage_log TokenUsage_log_company_info_id_fkey; Type: FK CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."TokenUsage_log"
    ADD CONSTRAINT "TokenUsage_log_company_info_id_fkey" FOREIGN KEY (company_info_id) REFERENCES dbo."CompanyInfo_master"(company_info_id) ON DELETE CASCADE;


--
-- Name: TokenUsage_log TokenUsage_log_message_id_fkey; Type: FK CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."TokenUsage_log"
    ADD CONSTRAINT "TokenUsage_log_message_id_fkey" FOREIGN KEY (message_id) REFERENCES agent."Chat_message"(message_id) ON DELETE SET NULL;


--
-- Name: TokenUsage_log TokenUsage_log_model_id_fkey; Type: FK CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."TokenUsage_log"
    ADD CONSTRAINT "TokenUsage_log_model_id_fkey" FOREIGN KEY (model_id) REFERENCES dbo."Model_master"(id) ON DELETE SET NULL;


--
-- Name: TokenUsage_log TokenUsage_log_session_id_fkey; Type: FK CONSTRAINT; Schema: agent; Owner: -
--

ALTER TABLE ONLY agent."TokenUsage_log"
    ADD CONSTRAINT "TokenUsage_log_session_id_fkey" FOREIGN KEY (session_id) REFERENCES agent."Chat_session"(session_id) ON DELETE SET NULL;


--
-- Name: CompanyInfo_ModelDeployment CompanyInfo_ModelDeployment_company_info_id_fkey; Type: FK CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."CompanyInfo_ModelDeployment"
    ADD CONSTRAINT "CompanyInfo_ModelDeployment_company_info_id_fkey" FOREIGN KEY (company_info_id) REFERENCES dbo."CompanyInfo_master"(company_info_id) ON DELETE CASCADE;


--
-- Name: CompanyInfo_ModelDeployment CompanyInfo_ModelDeployment_model_id_fkey; Type: FK CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."CompanyInfo_ModelDeployment"
    ADD CONSTRAINT "CompanyInfo_ModelDeployment_model_id_fkey" FOREIGN KEY (model_id) REFERENCES dbo."Model_master"(id) ON DELETE RESTRICT;


--
-- Name: ScopeCompany_map ScopeCompany_map_company_info_id_fkey; Type: FK CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."ScopeCompany_map"
    ADD CONSTRAINT "ScopeCompany_map_company_info_id_fkey" FOREIGN KEY (company_info_id) REFERENCES dbo."CompanyInfo_master"(company_info_id) ON DELETE CASCADE;


--
-- Name: ScopeCompany_map ScopeCompany_map_scope_key_fkey; Type: FK CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."ScopeCompany_map"
    ADD CONSTRAINT "ScopeCompany_map_scope_key_fkey" FOREIGN KEY (scope_key) REFERENCES public.dashboard_scopes(scope_key) ON DELETE CASCADE;


--
-- Name: User_AD_master User_AD_master_default_company_fkey; Type: FK CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."User_AD_master"
    ADD CONSTRAINT "User_AD_master_default_company_fkey" FOREIGN KEY (default_company) REFERENCES dbo."CompanyInfo_master"(company_info_id) ON DELETE RESTRICT;


--
-- Name: User_master User_master_default_company_fkey; Type: FK CONSTRAINT; Schema: dbo; Owner: -
--

ALTER TABLE ONLY dbo."User_master"
    ADD CONSTRAINT "User_master_default_company_fkey" FOREIGN KEY (default_company) REFERENCES dbo."CompanyInfo_master"(company_info_id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--


